### ISSUE TITLE
Does it support Payara, Weblogic

### ISSUE THREAD

**Issue by nvawoon** [cstroe/yajsw#2]
I have fully configured as a service for tomcat, but does it support payara? Or weblogic

**Comment by cstroe** [comment]
@nvawoon I don't know, I don't have experience with any of those technology stacks.

**Comment by nvawoon** [comment]
Maybe I am still not clear about this yajsw. Since Tomcat has it's own service installation, why still need this? Is this wrapper more for executable jar ?

**Comment by cstroe** [comment]
The main functionality of this project is that it allows you to take any Java application and turn it into a service.  For more information see the [Features](http://yajsw.sourceforge.net/#mozTocId945046) section on the official website: http://yajsw.sourceforge.net/

This repository is an unofficial mirror of the SVN repository.

**Comment by nvawoon** [comment]
Noted. Thanks
